### ISSUE TITLE
Blue dot pattern on TIFF and PPM output

### ISSUE THREAD

**Issue by tealeg** [rolkar/x3f#3]
First, I'd like to thank you heartily for this code.  I'm a 100% linux user, and I'm seriously considering buying a Sigma DP2 Quattro.  The only stumbling block for me is RAW support.  Your code is the best I've seen thus far.

I don't yet own the camera, but I tried your code on some sample pictures from the DP2 Quattro.  They can be converted to PPM and TIFF successfully.  However, across the image there's a blue pixel in a regular pattern (about once every 20 pixels horizontally, and every 4 pixels vertically).  This, of course, could be some deliberate watermarking that I'm not aware off, but I have no other files to check against.
 
They're not my images, but they are publicly available here, and explicitly provided as samples:
http://www.magezinepublishing.com/equipment/images/equipment/dp2-Quattro-5446/raw/SDIM0010.X3F
http://www.magezinepublishing.com/equipment/images/equipment/dp2-Quattro-5446/raw/SDIM0046.X3F

**Comment by LibRaw** [comment]
This is autofocus(?) or dynamic range estimation (?) pixels. These pixels need some interpolation code (not present in x3f tools AFAIK)

**Comment by tealeg** [comment]
@LibRaw - yes that would make sense.

**Comment by rolkar** [comment]
HI there - quite right - those are dynamic range extending dots. Sigma/Foveon has a patent on such a technique. Personally I think it is a bit scary, because then there is no detail in the over exposed image.

Other than that - the image is not converted to RGB. It is the RAW data. So - if you want to make pictures, you either have to make non correct color pictures or try to do some manual conversion.

In the company Kalpanika we are trying to fix this, but that is another story.

**Comment by rolkar** [comment]
No issue any more
